version: '2'
services:
  php54:
    image: lastcallmedia/php:5.4
    build:
      context: ./php54
      dockerfile: Dockerfile

  php54_dev:
    image: lastcallmedia/php:5.4-dev
    build:
      context: ./php54
      dockerfile: Dockerfile.dev

  php55:
    image: lastcallmedia/php:5.5
    build:
      context: ./php55
      dockerfile: Dockerfile

  php55_dev:
    image: lastcallmedia/php:5.5-dev
    build:
      context: ./php55
      dockerfile: Dockerfile.dev

  php56:
    image: lastcallmedia/php:5.6
    build:
      context: ./php56
      dockerfile: Dockerfile

  php56_dev:
    image: lastcallmedia/php:5.6-dev
    build:
      context: ./php56
      dockerfile: Dockerfile.dev

  php70:
    image: lastcallmedia/php:7.0
    build:
      context: ./php70
      dockerfile: Dockerfile

  php70_dev:
    image: lastcallmedia/php:7.0-dev
    build:
      context: ./php70
      dockerfile: Dockerfile.dev

  php71:
      image: lastcallmedia/php:7.1
      build:
        context: ./php71
        dockerfile: Dockerfile

  php71_dev:
    image: lastcallmedia/php:7.1-dev
    build:
      context: ./php71
      dockerfile: Dockerfile.dev