#!/bin/sh
set -e

# Write overrides to PHP and Apache. This is incompatible with starting the container
# with any user other than root, but that's not advised for the PHP Apache container
# anyway.

# PHP 7.3 is the first version that uses Xdebug 3; it's easier to check
# the php version in here than the Xdebug version
php_at_least_7_3=$(php -r 'echo version_compare(PHP_VERSION, "7.3") >= 0;')

PHP_AT_LEAST_7_3=$php_at_least_7_3 dockerize \
  -template /templates/php.overrides.tmpl:$PHP_INI_DIR/conf.d/99-runtime.ini \
  -template /templates/mpm_prefork.conf.tmpl:/etc/apache2/mods-enabled/mpm_prefork.conf

# Toggle XDebug completely on and off at runtime
# Enable Xdebug by setting XDEBUG_ENABLE=1.
if [ -z "$XDEBUG_ENABLE" ] || [ "$XDEBUG_ENABLE" -eq "0" ]; then
  rm -f $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini
else
  docker-php-ext-enable xdebug
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi
exec "$@"
