name: Commit
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "7.0"
          - "7.0-dev"
          - "7.1"
          - "7.1-dev"
          - "7.2"
          - "7.2-dev"
          - "7.3"
          - "7.3-dev"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build Image
        run: docker build -t lastcallmedia/php:${{ matrix.version }} ./${{ matrix.version }}
      - name: Test Image
        uses: ./.github/actions/container-structure-test
        with:
          image: lastcallmedia/php:${{ matrix.version }}
          config: ./${{ matrix.version }}/test.yml
