name: Commit
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [7.0, 7.1, 7.2, 7.3]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build Image
        run: docker build -t lastcallmedia/php:${{ matrix.version }} ./${{ matrix.version }}
      - name: Test Image
        uses: docker://gcr.io/gcp-runtimes/container-structure-test:latest
        run: container-structure-test test --image lastcallmedia/php:${{ matrix.version }} --config ./${{ matrix.version }}/test.yml --save
